### ISSUE TITLE
Hypershift install on my AWS cluster generates a panic

### ISSUE THREAD

**Issue by dciancio** [openshift/hypershift#156]
Installing the operator as follows fails:

```
$ hypershift install 
I0414 13:05:31.372856 1535925 request.go:655] Throttling request took 1.027699017s, request: GET:https://api.myclustername.mydomain:6443/apis/apiextensions.k8s.io/v1?timeout=32s
applied CustomResourceDefinition /hostedclusters.hypershift.openshift.io
applied CustomResourceDefinition /nodepools.hypershift.openshift.io
applied CustomResourceDefinition /hostedcontrolplanes.hypershift.openshift.io
applied CustomResourceDefinition /externalinfraclusters.hypershift.openshift.io
applied CustomResourceDefinition /machineconfigservers.hypershift.openshift.io
panic: timed out waiting for the condition

goroutine 1 [running]:
github.com/openshift/hypershift/cmd/install.NewCommand.func1(0xc000310b00, 0x32a6b58, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/openshift/hypershift@v0.0.0-20210413151642-3a97fd9b1e64/cmd/install/install.go:75 +0x38c
github.com/spf13/cobra.(*Command).execute(0xc000310b00, 0x32a6b58, 0x0, 0x0, 0xc000310b00, 0x32a6b58)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000310840, 0xc00069bf60, 0x1, 0x1)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/home/user/go/pkg/mod/github.com/openshift/hypershift@v0.0.0-20210413151642-3a97fd9b1e64/main.go:44 +0x176

```

Installing it using this method works fine and creates all the required resources:
```
$ hypershift install --render | oc apply -f -
customresourcedefinition.apiextensions.k8s.io/hostedclusters.hypershift.openshift.io created
customresourcedefinition.apiextensions.k8s.io/nodepools.hypershift.openshift.io created
customresourcedefinition.apiextensions.k8s.io/hostedcontrolplanes.hypershift.openshift.io created
customresourcedefinition.apiextensions.k8s.io/externalinfraclusters.hypershift.openshift.io created
customresourcedefinition.apiextensions.k8s.io/machineconfigservers.hypershift.openshift.io created
namespace/hypershift created
serviceaccount/operator created
clusterrole.rbac.authorization.k8s.io/hypershift-operator created
clusterrolebinding.rbac.authorization.k8s.io/hypershift-operator created
deployment.apps/operator created
customresourcedefinition.apiextensions.k8s.io/clusters.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/machinedeployments.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/machinehealthchecks.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/machines.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/machinesets.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsclusters.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsmachinepools.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsmachines.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsmachinetemplates.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsmanagedclusters.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com created
customresourcedefinition.apiextensions.k8s.io/etcdbackups.etcd.database.coreos.com created
customresourcedefinition.apiextensions.k8s.io/etcdrestores.etcd.database.coreos.com created

```

Any ideas what could be wrong?

**Comment by ironcladlou** [comment]
Please feel free to re-open with a reproducer if this is still an issue
