### ISSUE TITLE
hypershift-operator crashed during the hostedcluster delete flow

### ISSUE THREAD

**Issue by mkumatag** [openshift/hypershift#2072]
Have seen operator crashing with SIGSEGV with following stack trace

```shell
{"level":"info","ts":"2023-01-25T08:26:07Z","msg":"successfully reconciled","controller":"hostedcluster","controllerGroup":"hypershift.openshift.io","controllerKind":"HostedCluster","hostedCluster":{"name":"example","namespace":"clusters"},"namespace":"clusters","name":"example","reconcileID":"a6f60bdf-d10c-42ab-80f2-7d2d08584b44"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2af181b]

goroutine 500 [running]:
main.clusterGuestCloudResourcesDeletionTime(0xc001802c00)
	/hypershift/hypershift-operator/metrics.go:359 +0x19b
main.(*hypershiftMetrics).observeHostedClusters(0xc000660dc0, 0xc0067da700)
	/hypershift/hypershift-operator/metrics.go:278 +0x19ac
main.(*hypershiftMetrics).collect(0xc000660dc0, {0x36bfb38, 0xc000da13c0})
	/hypershift/hypershift-operator/metrics.go:136 +0x21d
main.(*hypershiftMetrics).Start(0xc000660dc0, {0x36bfb38, 0xc000da13c0})
	/hypershift/hypershift-operator/metrics.go:124 +0x125
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0xc00005cb60)
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:219 +0x152
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:203 +0x1db
```

**Comment by mkumatag** [comment]
I guess this is happening while fetching the `DeletionTimestamp` which is missing, good to have null check before accessing the field. IsZero() function can be used before accessing the field.

**Comment by bryan-cox** [comment]
Hello @mkumatag, I put in a null check for this and the PR merged early today. Please let me know if you see this again or if it's resolved.

**Comment by mkumatag** [comment]
Thanks @bryan-cox, merged PR should fix this issue.
