### ISSUE TITLE
Control plane operator crashing during cluster destroy for platforms other than AWS

### ISSUE THREAD

**Issue by dharaneeshvrd** [openshift/hypershift#2164]
During destroy `destroyAWSDefaultSecurityGroup` [func](https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L3714) is not handling the platform check like its handled during create [here](https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L3550).

Its causing crash in control plane operator during destroy.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2f93e23]

goroutine 732 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x2d9
panic({0x344fee0, 0x53fa320})
	/usr/lib/golang/src/runtime/panic.go:890 +0x267
github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane.(*HostedControlPlaneReconciler).destroyAWSDefaultSecurityGroup(0xc000aac0b0, {0x3f0ffc8, 0xc0004c6330}, 0xc00007fc00)
	/hypershift/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go:3651 +0x203
github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane.(*HostedControlPlaneReconciler).Reconcile(0xc000aac0b0, {0x3f0ffc8, 0xc0004c6330}, {{{0xc0005c03f0, 0x25}, {0xc0008efe80, 0x1c}}})
	/hypershift/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go:241 +0x1d2f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000571180, {0x3f0ffc8, 0xc0004c6330}, {{{0xc0005c03f0, 0x25}, {0xc0008efe80, 0x1c}}})
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0x172
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000571180, {0x3f0ffc8, 0xc0004c6330}, {0x3577e20, 0xc000151600})
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x3d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000571180, {0x3f0ff20, 0xc000bd13c0})
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0xdc
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x4d9
dharaneesh@Dharaneeshwarans-MacBook-Pro-2 hypershift % 
```

**Comment by csrwng** [comment]
Fixed by #2164
