### ISSUE TITLE
machine health checks causing capi controller to panic

### ISSUE THREAD

**Issue by csrwng** [openshift/hypershift#471]
I enabled autorepair on my main nodepool, and I'm seeing this in the capi controller:
```
I0913 21:06:15.337958       1 machinehealthcheck_targets.go:151] controller-runtime/manager/controller/machinehealthcheck "msg"="Target is unhealthy: machine has no node" "Target"="clusters-cewong-guest/cewong-guest/cewong-guest-091317-c-da900ffa-cewong-guest-84dd6dbcbd-j7q48/" "cluster"="cewong-guest-091317" "name"="cewong-guest" "namespace"="clusters-cewong-guest" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineHealthCheck" "duration"="&Duration{Duration:10m0s,}"
panic: key is not a string: null

goroutine 781 [running]:
k8s.io/klog/v2/klogr.flatten(0xc000b9f920, 0x6, 0x6, 0xc0008642c0, 0xa6)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klogr/klogr.go:158 +0x62e
k8s.io/klog/v2/klogr.klogger.Info(0x3, 0x0, 0xc00088c240, 0x38, 0xc001528780, 0xa, 0xa, 0x1b830d7, 0x9, 0x1b969b8, ...)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klogr/klogr.go:201 +0x625
sigs.k8s.io/cluster-api/controllers.(*MachineHealthCheckReconciler).reconcile(0xc0002e7220, 0x1dbd618, 0xc000b054a0, 0x1dc70d8, 0xc000426460, 0xc0001fe000, 0xc000d145a0, 0x13, 0xc0001fe000, 0x0, ...)
        /workspace/controllers/machinehealthcheck_controller.go:285 +0x12d4
```

**Comment by csrwng** [comment]
@enxebre I see this was fixed by https://github.com/kubernetes-sigs/cluster-api/pull/5110 Thank you! 
When can we pick up that fix? I don't see it included in a release.
